import pandas as pd
from sklearn.model_selection import train_test_split

def load_and_clean_data(filepath: str):
    """
    Loads the breast cancer dataset, removes irrelevant columns, 
    and encodes the target variable.
    """
    # Load dataset
    df = pd.read_csv(filepath)
    
    # Drop columns typically generated by Kaggle exports or indices
    if 'Unnamed: 32' in df.columns:
        df = df.drop(columns=['Unnamed: 32'])
    if 'id' in df.columns:
        df = df.drop(columns=['id'])
        
    # Encode target: Malignant = 1, Benign = 0
    if 'diagnosis' in df.columns:
        df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})
        
    return df

def prepare_data_splits(df: str, target_col: str = 'diagnosis', test_size: float = 0.2, random_state: int = 42):
    """
    Splits the dataframe into training and testing features and labels.
    """
    X = df.drop(columns=[target_col])
    y = df[target_col]
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y
    )
    return X_train, X_test, y_train, y_test